pull_request_rules:
  - name: Automatic merge dependabot
    conditions:
      - author~=^dependabot\[bot\]$
      - base=main
      - -closed
      - -conflict
      - check-success=Analyze (javascript)
      - check-success=testflow
      - check-success=test (14)
      - check-success=test (16)
      - check-success=test (18)
    actions:
      merge:
        method: merge
  - name: Automatic merge code owner
    conditions:
      - author~=^kamontat$
      - -draft
      - -conflict
      - -closed
      - label!=wip
      - -title~=^wip
      - check-success=Analyze (javascript)
      - check-success=testflow
      - check-success=test (14)
      - check-success=test (16)
      - check-success=test (18)
    actions:
      merge:
        method: merge
