pull_request_rules:
  - name: Automatic merge dependabot
    conditions:
      - author~=^dependabot\[bot\]$
      - base=main
      - -closed
      - check-success=Analyze (javascript)
      - check-success=buildflow
      - check-success=test (12)
      - check-success=test (14)
      - check-success=test (17)
    actions:
      merge:
        method: merge
