pull_request_rules:
  - name: Automatic merge dependabot
    conditions:
      - author~=^dependabot\[bot\]$
      - base=main
      - -closed
      - -conflict
      - check-success=analyze (javascript)
      - check-success=default
      - check-success=nodes (14)
      - check-success=nodes (16)
      - check-success=nodes (18)
    actions:
      merge:
        method: merge
  - name: Automatic merge code owner
    conditions:
      - author~=^kamontat$
      - -draft
      - -conflict
      - -closed
      - label!=wip
      - -title~=^wip
      - check-success=analyze (javascript)
      - check-success=default
      - check-success=nodes (14)
      - check-success=nodes (16)
      - check-success=nodes (18)
    actions:
      merge:
        method: merge
