name: "Setup Project"
description: "For download and install project dependencies"
inputs:
  node_version:
    description: "Specify nodejs version"
    required: true
  with_build:
    description: "Build packages, you SHOULD NOT USE if you plan to collect coverage report"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: "https://registry.npmjs.org"
        cache: yarn
        cache-dependency-path: "**/yarn.lock"
    - name: Install dependencies
      run: yarn install
      shell: bash
    - name: Bootstrap packages
      run: yarn packages bootstrap
      shell: bash
    - name: Compile and build packages
      if: ${{ inputs.with_build == 'true' }}
      run: yarn packages build
      shell: bash
