settings:
  hack: false
  config:
    disabled: false
  log:
    level: info
  commit:
    key:
      enabled: true
      required: true
      prompt:
        select:
          page: 5
          suggestion: false
          values:
          - key: feat
            text: Introducing new features
          - key: perf
            text: Improving user experience / usability / reliablity
          - key: fix
            text: Fixing a bug
          - key: chore
            text: Other changes unrelated to user/client
        input: null
    scope:
      enabled: true
      required: false
      prompt:
        select:
          page: 5
          suggestion: false
          values:
          - key: test
            text: Add, Modify or remove test case
          - key: lint
            text: Code styles
          - key: config
            text: Configuration
        input: null
    title:
      enabled: true
      required: true
      prompt:
        select: null
        input:
          max: 75
          multiline: false
    message:
      enabled: false
      required: false
      prompt:
        select: null
        input:
          max: 200
          multiline: true
version: 5
