name: "Deployment"
description: "For deploy changed packages"
inputs:
  github_token:
    description: "Github Token to release new version"
    required: true
  npm_token:
    description: "NPM Token to publish package"
    required: true
  with_build:
    description: "Build packages"
    required: false
    default: "true"
  release_type:
    description: "Release type"
    required: false
    default: "live"
  with_git:
    description: "Update git settings"
    required: false
    default: "false"
  git_username:
    description: "username of git user"
    required: false
    default: ""
  git_email:
    description: "Email of git user"
    required: false
    default: ""
  with_gpg:
    description: "Update GPG settings"
    required: false
    default: "false"
  gpg_private_key_base64:
    description: "Private key of GPG in base64"
    required: false
    default: ""
  gpg_signing_key:
    description: "Signing key of GPG"
    required: false
    default: ""
  gpg_identify_key:
    description: "Identify key of GPG"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Compile and build packages
      if: ${{ inputs.with_build == 'true' }}
      run: yarn packages build
      shell: bash

    - name: Check git status
      run: git status --short
      shell: bash
    - name: Cleanup all changes
      run: git checkout .
      shell: bash

    - name: Setup GPG
      if: ${{ inputs.with_gpg == 'true' }}
      run: ${{ github.action_path }}/setup_gpg.sh
      shell: bash
      env:
        GPG_PRIVATE_KEY_BASE64: ${{ inputs.gpg_private_key_base64 }}
        GPG_SIGNING_KEY: ${{ inputs.gpg_signing_key }}
    - name: Setup git
      if: ${{ inputs.with_git == 'true' }}
      run: ${{ github.action_path }}/setup_git.sh
      shell: bash
      env:
        GIT_USERNAME: ${{ inputs.git_username }}
        GIT_EMAIL: ${{ inputs.git_email }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - name: Setup npm token
      run: ${{ github.action_path }}/setup_npm.sh
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm_token }}

    - name: Check package to deploy
      run: yarn packages change
      shell: bash
    - name: Increase new package version
      run: yarn packages version ${{ inputs.release_type }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        NPM_TOKEN: ${{ inputs.npm_token }}
    - name: Publish new package
      run: yarn packages publish ${{ inputs.release_type }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        NPM_TOKEN: ${{ inputs.npm_token }}
    - name: Publish documentation
      run: yarn packages docs
      shell: bash

    - name: Cleanup git
      if: ${{ inputs.with_git == 'true' }}
      run: ${{ github.action_path }}/cleanup_git.sh
      shell: bash
    - name: Cleanup GPG
      if: ${{ inputs.with_gpg == 'true' }}
      run: ${{ github.action_path }}/cleanup_gpg.sh
      shell: bash
      env:
        GPG_IDENTIFY_KEY: ${{ inputs.gpg_identify_key }}
    - name: Setup npm token
      run: ${{ github.action_path }}/cleanup_npm.sh
      shell: bash
