name: analysis-pull-request

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup
        with:
          with_build: true
      - name: Danger JS
        uses: danger/danger-js@11.1.2
        with:
          args: --dangerfile .dangerjs/pr-analysis.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
