name: Default

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release_type:
        description: manually release packages with type
        required: false
        default: live
        type: choice
        options:
          - live
          - rc
          - beta
          - alpha

defaults:
  run:
    shell: bash

jobs:
  # this should contains only unit testing on several node version to ensure backward compatible
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 17]
    steps:
      - uses: ./.github/actions/setup
        with:
          with_build: true
          node_version: ${{ matrix.node-version }}
      - name: Testing unittest
        run: yarn packages test

  # run buildflow on latest node lts version only
  # this should contains whole flow of lint, test, build, and deploy package
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
        with:
          shallow_clone: false
          with_build: true
          node_version: "16"

      - name: Check style
        run: yarn packages lint
      - name: Run unit test
        run: yarn packages test
      - name: Run mutator test
        run: yarn packages test:mutator
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
      - name: Scan sourcecode
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Check git status
        run: git status --short
        if: github.ref_name == 'main' && github.repository == 'kamontat/kcutils'
      - name: Cleanup all changes
        run: git checkout .
        if: github.ref_name == 'main' && github.repository == 'kamontat/kcutils'
