name: Default

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  # Test and report result in sonarqube (run only primary node version)
  testflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup project
        uses: ./.github/actions/setup
        with:
          node_version: 16
      - name: Start testflow
        uses: ./.github/actions/testflow
        with:
          with_lint: true
          with_unittest: true
          with_sonar: true
          github_apikey: ${{ secrets.GITHUB_TOKEN }}
          sonar_apikey: ${{ secrets.SONAR_TOKEN }}

  # Test on different node version to ensure backward compatible
  test:
    runs-on: ubuntu-latest
    needs:
      - testflow
    strategy:
      matrix:
        node-version: [12, 14, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Setup project
        uses: ./.github/actions/setup
        with:
          with_build: true
          node_version: ${{ matrix.node-version }}
      - name: Start testflow
        uses: ./.github/actions/testflow
        with:
          with_unittest: true
