name: deployment

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: manually release packages with type
        required: false
        default: live
        type: choice
        options:
          - live
          - rc
          - beta
          - alpha
  schedule:
    - cron: "30 1 * * 1" # https://crontab.guru/#30_1_*_*_1

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'kamontat/kcutils' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Setup project
        uses: ./.github/actions/setup
        with:
          with_build: true
      - uses: ./.github/actions/lint
        with:
          collect_report: true
      - uses: ./.github/actions/unit-test
        with:
          collect_report: true
      - uses: ./.github/actions/mutator-test
        with:
          apikey: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
          collect_report: true
      - name: Deployment
        uses: ./.github/actions/deployment
        with:
          release_type: ${{ github.event.inputs.release_type || 'live' }}
          with_git: true
          git_username: ${{ secrets.GIT_USERNAME }}
          git_email: ${{ secrets.GIT_EMAIL }}
          with_gpg: true
          gpg_private_key_base64: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}
          gpg_signing_key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg_identify_key: ${{ secrets.GPG_IDENTIFY_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
