name: PR Analysis

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup
        with:
          with_build: true
          node_version: 16
      - name: Danger JS
        run: yarn danger ci --dangerfile .dangerjs/pr-analysis.ts
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
