name: Schedule Task

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: manually release packages with type
        required: false
        default: live
        type: choice
        options:
          - live
          - rc
          - beta
          - alpha
  schedule:
    - cron: "30 1 * * 1" # https://crontab.guru/#30_1_*_*_1

defaults:
  run:
    shell: bash

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup project
        uses: ./.github/actions/setup
        with:
          with_build: true
          node_version: 16
      - name: Start testflow
        uses: ./.github/actions/testflow
        with:
          with_lint: true
          with_unittest: true
          with_mutator_test: false # TODO: disable this due to fix didn't deploy yet. https://github.com/stryker-mutator/stryker-js/pull/3313
          mutator_apikey: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
      - name: Deployment
        uses: ./.github/actions/deployment
        with:
          release_type: ${{ inputs.release_type }}
          with_git: true
          git_username: ${{ secrets.GIT_USERNAME }}
          git_email: ${{ secrets.GIT_EMAIL }}
          with_gpg: true
          gpg_private_key_base64: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}
          gpg_signing_key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg_identify_key: ${{ secrets.GPG_IDENTIFY_KEY }}
