name: test

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set SHAs for "nx affected"
        uses: nrwl/nx-set-shas@v3
      - name: Setup project
        uses: ./.github/actions/setup
        with:
          with_build: true
      - uses: ./.github/actions/lint
        with:
          collect_report: true
      - uses: ./.github/actions/unit-test
        with:
          collect_report: true
      - uses: ./.github/actions/sonar
        with:
          github_apikey: ${{ secrets.GITHUB_TOKEN }}
          sonar_apikey: ${{ secrets.SONAR_TOKEN }}

  nodes:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set SHAs for "nx affected"
        uses: nrwl/nx-set-shas@v3
      - name: Setup project
        uses: ./.github/actions/setup
        with:
          with_build: true
          node_version: ${{ matrix.node-version }}
      - uses: ./.github/actions/unit-test
        with:
          collect_report: true
